name: CppCheck scan

on:
  pull_request:
    branches: ["master"]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan
        uses: chmorgan/cppcheck-action@v1.4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}