name: Integration Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build tests
        run: |
          set -e
          ./build-tests.sh
      - name: Run tests
        run: |
          set -e
          ./run-tests.sh
